server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g1-sprint2
    username: halykfinance
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true